version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://server:5000
    depends_on:
      - server

  server:
    build:
      context: ./server-test
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - minio
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DatabaseContext=Host=postgres;Database=interviewhub;Username=ihubuser;Password=ih_strong_pass_123!
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=ihub_minio_access
      - Minio__SecretKey=ihub_minio_secret_123!

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: interviewhub
      POSTGRES_USER: ihubuser
      POSTGRES_PASSWORD: ih_strong_pass_123!
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ihub_minio_access
      MINIO_ROOT_PASSWORD: ihub_minio_secret_123!
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  minio-data:
