version: '3.8'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://server:80
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - minio
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DatabaseContext=Host=postgres;Database=interviewhub;Username=ihubuser;Password=ih_strong_pass_123!
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=ihub_minio_access
      - Minio__SecretKey=ihub_minio_secret_123!
      - GigaChat__SecretKey=ZDUyZTMxNjItMDVhNy00Y2U4LTg1NTctMmM4M2Q3MWE1M2NkOjE0ZDAwYmFkLTgwN2ItNDkzOC1hMTA5LTI1NTgxNTBmMDk0ZQ==
      - GigaChat__ClientId=d52e3162-05a7-4ce8-8557-2c83d71a53cd
      - GigaChat__Scope=GIGACHAT_API_PERS
      - GigaChat__Url=https://gigachat.devices.sberbank.ru/api/v1
      - GigaChat__AuthUrl=https://ngw.devices.sberbank.ru:9443/api/v2/oauth
  postgres:
    image: postgres:14
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: interviewhub
      POSTGRES_USER: ihubuser
      POSTGRES_PASSWORD: ih_strong_pass_123!
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ihub_minio_access
      MINIO_ROOT_PASSWORD: ihub_minio_secret_123!
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  minio-data:

